
services:
    BeyondBlueSky\LibJWT\DependencyInjection\JWTServiceExtension:
        class: BeyondBlueSky\LibJWT\DependencyInjection\JWTServiceExtension
        public: true
        autowire: true
        
        
